// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQK7VrMXh8JpEhBVrXhGfQN_eddJCPuao',
    appId: '1:920013344479:web:0ef260535e0ca92cd4e36a',
    messagingSenderId: '920013344479',
    projectId: 'socialapp-9a111',
    authDomain: 'socialapp-9a111.firebaseapp.com',
    storageBucket: 'socialapp-9a111.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj7kS3TLHNE0kULQyml2ySlJ1bOiJXbwE',
    appId: '1:920013344479:android:4df7c3ebfc0b0503d4e36a',
    messagingSenderId: '920013344479',
    projectId: 'socialapp-9a111',
    storageBucket: 'socialapp-9a111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF258cLurHYqxrQNYraMb9juIoaC1ayZE',
    appId: '1:920013344479:ios:a62ad79f01cf0b5dd4e36a',
    messagingSenderId: '920013344479',
    projectId: 'socialapp-9a111',
    storageBucket: 'socialapp-9a111.appspot.com',
    iosClientId: '920013344479-9avku0f371r0fd7qg1idg998vmblhqon.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF258cLurHYqxrQNYraMb9juIoaC1ayZE',
    appId: '1:920013344479:ios:a62ad79f01cf0b5dd4e36a',
    messagingSenderId: '920013344479',
    projectId: 'socialapp-9a111',
    storageBucket: 'socialapp-9a111.appspot.com',
    iosClientId: '920013344479-9avku0f371r0fd7qg1idg998vmblhqon.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );
}
